// Generated by Lux — `lux types`. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | Json[]
  | { [key: string]: Json };

export interface Profiles {
  id: string;
  created_at: number | null;
  username: string | null;
  full_name: string | null;
}

export interface Teams {
  id: string;
  created_at: number | null;
  slug: string;
  name: string;
  created_by: string | null;
}

export interface Members {
  id: string;
  role: string | null;
  created_at: number | null;
  team_id: string | null;
  user_id: string | null;
}

export interface Invites {
  id: string;
  email: string | null;
  team_id: string | null;
  role: string | null;
}

export type Database = {
  profiles: Profiles;
  teams: Teams;
  members: Members;
  invites: Invites;
};
